### ISSUE TITLE
Create a folder named "sounds" and move all audio files used in tasks into it

### ISSUE THREAD

**Issue by khaledhazime** [robofeiathome/speech_recognition#5]
In order to better organize the audio files used in tasks, we should create a folder called "sounds" and move all of the audio files to that folder. This will make it easier to locate the files when needed and ensure that they are all in one central location. It is recommended that this be done as soon as possible to prevent any confusion or loss of files in the future.

**Comment by khaledhazime** [comment]
Also, make sure all sounds are in .mp3 format.

**Comment by PedroTolardo** [comment]
Day (25/04):
I started to create a new folder that contains all the functions to play audio, such as beep and the voice of Hera.
Tomorrow I will add the functions of the new class to the code.

**Comment by khaledhazime** [comment]
@PedroTolardo , I've already created a function to this [here](https://github.com/robofeiathome/hera_tasks/blob/b17f9a878e03128dedf3f4a1d8b5b37d0f9cc4a1/tasks/methods/Speech.py#L63-L68). Just need the folder with the audio files.

**Comment by PedroTolardo** [comment]
I added the folder containing the audio files, along with the Receptionist and Quiz codes, to the Speech_receptionist branch on the hera_task repository.
